//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsCollection.Desktop.UI.Modules.BulkUpdate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BulkUpdateModuleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BulkUpdateModuleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsCollection.Desktop.UI.Modules.BulkUpdate.Resources.BulkUpdateModuleStrings", typeof(BulkUpdateModuleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string BeerComment {
            get {
                return ResourceManager.GetString("BeerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string BeerInfo {
            get {
                return ResourceManager.GetString("BeerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string BeerName {
            get {
                return ResourceManager.GetString("BeerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string BeerPrice {
            get {
                return ResourceManager.GetString("BeerPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string BeerSite {
            get {
                return ResourceManager.GetString("BeerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer style.
        /// </summary>
        public static string BeerStyle {
            get {
                return ResourceManager.GetString("BeerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer type.
        /// </summary>
        public static string BeerType {
            get {
                return ResourceManager.GetString("BeerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string BeerYear {
            get {
                return ResourceManager.GetString("BeerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle file name.
        /// </summary>
        public static string BottleFileName {
            get {
                return ResourceManager.GetString("BottleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle full size.
        /// </summary>
        public static string BottleFullSize {
            get {
                return ResourceManager.GetString("BottleFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle preview size.
        /// </summary>
        public static string BottlePreviewSize {
            get {
                return ResourceManager.GetString("BottlePreviewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle thumbnail size.
        /// </summary>
        public static string BottleThumbnailSize {
            get {
                return ResourceManager.GetString("BottleThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewery.
        /// </summary>
        public static string BreweryInfo {
            get {
                return ResourceManager.GetString("BreweryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update existing beers.
        /// </summary>
        public static string BulkUpdateBeersTabName {
            get {
                return ResourceManager.GetString("BulkUpdateBeersTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap file name.
        /// </summary>
        public static string CapFileName {
            get {
                return ResourceManager.GetString("CapFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap full size.
        /// </summary>
        public static string CapFullSize {
            get {
                return ResourceManager.GetString("CapFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap preview size.
        /// </summary>
        public static string CapPreviewSize {
            get {
                return ResourceManager.GetString("CapPreviewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap thumbnail size.
        /// </summary>
        public static string CapThumbnailSize {
            get {
                return ResourceManager.GetString("CapThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap type.
        /// </summary>
        public static string CapType {
            get {
                return ResourceManager.GetString("CapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label file name.
        /// </summary>
        public static string LabelFileName {
            get {
                return ResourceManager.GetString("LabelFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label full size.
        /// </summary>
        public static string LabelFullSize {
            get {
                return ResourceManager.GetString("LabelFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label preview size.
        /// </summary>
        public static string LabelPreviewSize {
            get {
                return ResourceManager.GetString("LabelPreviewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label thumbnail size.
        /// </summary>
        public static string LabelThumbnailSize {
            get {
                return ResourceManager.GetString("LabelThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during generation a beer view.
        /// </summary>
        public static string PrepareBeerViewForUpdatingError {
            get {
                return ResourceManager.GetString("PrepareBeerViewForUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateCollection {
            get {
                return ResourceManager.GetString("UpdateCollection", resourceCulture);
            }
        }
    }
}
