//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsCollection.Desktop.UI.Modules.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsCollection.Desktop.UI.Modules.Services.Resources.EventMessages", typeof(EventMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some aggregation data is missing.
        /// </summary>
        public static string DatabaseAggregationDataMissing {
            get {
                return ResourceManager.GetString("DatabaseAggregationDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data from the database ....
        /// </summary>
        public static string DatabaseFetchingRecords {
            get {
                return ResourceManager.GetString("DatabaseFetchingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images for processing.
        /// </summary>
        public static string ImageProcessingDataEmpty {
            get {
                return ResourceManager.GetString("ImageProcessingDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files and creating thumbnails ....
        /// </summary>
        public static string ImageProcessingInProgress {
            get {
                return ResourceManager.GetString("ImageProcessingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming beer images ....
        /// </summary>
        public static string RenamingBeerImages {
            get {
                return ResourceManager.GetString("RenamingBeerImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during image rename.
        /// </summary>
        public static string RenamingBeerImagesFailed {
            get {
                return ResourceManager.GetString("RenamingBeerImagesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer saved.
        /// </summary>
        public static string SavingBeerCompleted {
            get {
                return ResourceManager.GetString("SavingBeerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving beer ....
        /// </summary>
        public static string SavingBeerInProgress {
            get {
                return ResourceManager.GetString("SavingBeerInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavingDataIsEmpty.
        /// </summary>
        public static string SavingDataIsEmpty {
            get {
                return ResourceManager.GetString("SavingDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving beer in the database ....
        /// </summary>
        public static string SavingInDatabase {
            get {
                return ResourceManager.GetString("SavingInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading beer images ....
        /// </summary>
        public static string UploadingBeerImages {
            get {
                return ResourceManager.GetString("UploadingBeerImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during image upload.
        /// </summary>
        public static string UploadingBeerImagesError {
            get {
                return ResourceManager.GetString("UploadingBeerImagesError", resourceCulture);
            }
        }
    }
}
