//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsCollection.Desktop.UI.Modules.Home.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeModuleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeModuleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsCollection.Desktop.UI.Modules.Home.Resources.HomeModuleStrings", typeof(HomeModuleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle images.
        /// </summary>
        public static string BottleImages {
            get {
                return ResourceManager.GetString("BottleImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle images path.
        /// </summary>
        public static string BottleImagesPath {
            get {
                return ResourceManager.GetString("BottleImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap images.
        /// </summary>
        public static string CapImages {
            get {
                return ResourceManager.GetString("CapImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap images path.
        /// </summary>
        public static string CapImagesPath {
            get {
                return ResourceManager.GetString("CapImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate thumbnails.
        /// </summary>
        public static string GenerateThumbnails {
            get {
                return ResourceManager.GetString("GenerateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTabName {
            get {
                return ResourceManager.GetString("HomeTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label images.
        /// </summary>
        public static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label images path.
        /// </summary>
        public static string LabelImagesPath {
            get {
                return ResourceManager.GetString("LabelImagesPath", resourceCulture);
            }
        }
    }
}
